Homework-07 packer
Otus-DevOps-2017-11/andywow_infra pull request #3
Opened 2017-12-21 05:44 UTC by andywow

Homework-07. Работа с packer. Задания сделал. Вопросов пока нет =)

2017-12-21 08:03 UTC, andywow commented
Невнимательно читал про каталог files - создание systemd юнита перенести стоит туда, вечером подправлю

2017-12-21 16:01 UTC, andywow commented
Сделано. Хочу добавить, что отказался от своих старых скриптов из предыдущего ДЗ, которые представляли собой запускалку (runner.sh) и команды в текстовых файлах. В принципе можно было и с ними все реализовать, но не стал усложнять.

2017-12-22 21:39 UTC, vitkhab requested changes
Все классно! Запускается, работает. У меня небольшая просьба, немного доработать 
шаблоны и `variables.json.example`:
- Подумай, что сделать с `disk_name`. Пока это неработающая часть проекта.

Над чем можно поработать:
- Документация есть, но в минимальном объеме. Как пример куда можно развиваться https://goo.gl/me4MEX

Из плюсов:
- Выполнены оба задания со звездочками. Это клево!
- Вижу, что посмотрел на возможности `googlecompute` builder'а. Классно, что ты интересуешься.
- Еще раз отмечу разговор в слаке про переиспользование base-образа.

2017-12-22 21:39 UTC, vitkhab commented on packer/variables.json.example
> +    "gc_disk_name": "your-disk-name",
Параметр `disk_name` для `googlecompute` не работает. Диск для VM все равно создается со случайным именем, а `packer` старается снять образ с `disk_name`, которого нет. В причинах разбираться не стал.
Проще удалить этот атрибут. Я не знаю зачем нам может потребоваться задавать определенное имя диска который живет только во время сборки образа. Разве что удалить его вручную, если этого не сделает packer, но я бы этот вариант не рассматривал.

2017-12-22 21:39 UTC, vitkhab commented on packer/variables.json.example
> +    "gc_machine_type": "your-machine",
Предлагаю задать `gc_source_image_family` и `gc_machine_type` имеющие смысл значения по умолчанию: `ubuntu-1604-lts`, как наиболее вероятный вариант; `null` - чтобы явно указать на необходимость указать параметр; `Комментарий`, который дает большее понимание что это за атрибут.

2017-12-22 21:39 UTC, vitkhab commented on packer/ubuntu16.json
> +        "gc_project_id": "",
Предполагалось, что тут будет `null` (без кавычек). Круто, что и такой способ нашел решить задачу =)

2017-12-23 07:51 UTC, andywow commented on packer/variables.json.example
> +    "gc_disk_name": "your-disk-name",
На сколько я понял, packer пытаеся сохранить образ, который он создал на этом диске. Если диска нет, то падает с ошибкой, если диск есть, по сохраняет на нем.

2017-12-23 08:46 UTC, vitkhab commented on packer/variables.json.example
> +    "gc_disk_name": "your-disk-name",
Да, но `packer` не создает этот диск, не подключает его к созданной VM, не проверяет его наличие. Он создаст VM, произведет все необходимые операции, но образ будет делать с "левого" диска. Это явно баг.

2017-12-23 08:58 UTC, andywow commented
disk_name убрал из описания. Документацию написал более подробную.

2017-12-25 09:00 UTC, vitkhab approved these changes
Молодец! Все отлично!

2017-12-25 09:17 UTC, merged